apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: architecture-diagram
  description: "RH Dev Hub"
  annotations:
    # this could also be `url:<url>` if the documentation isn't in the same location
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: experimental
  owner: dev-hub-team
  system: Architecture
